[
  {
    "id": "Arrow-Py #1191",
    "type": "Logical",
    "url": "https://github.com/arrow-py/arrow/issues/1191",
    "lead": "Gabe Sherman",
    "date": "2024-10-04",
    "desc": "IndexError in DateTimeParser.parse"
  },
  {
    "id": "Astroid #2734",
    "type": "Logical",
    "url": "https://github.com/pylint-dev/astroid/issues/2734",
    "lead": "Gabe Sherman",
    "date": "2025-05-12",
    "desc": "IndexError when calling extract_node"
  },
  {
    "id": "autoflake #325",
    "type": "Logical",
    "url": "https://github.com/PyCQA/autoflake/issues/325",
    "lead": "Gabe Sherman",
    "date": "2025-04-25",
    "desc": "Index out of range error in autoflake.fix_code"
  },
  {
    "id": "autoflake #326",
    "type": "Logical",
    "url": "https://github.com/PyCQA/autoflake/issues/326",
    "lead": "Gabe Sherman",
    "date": "2025-05-04",
    "desc": "TypeError: unhashable type errors in filter_unused_variable"
  },
  {
    "id": "Babel #1134",
    "type": "Logical",
    "url": "https://github.com/python-babel/babel/issues/1134",
    "lead": "Gabe Sherman",
    "date": "2024-09-24",
    "desc": "List index out of range error in PoFileParser._add_message"
  },
  {
    "id": "CPython #125648",
    "type": "Logical",
    "url": "https://github.com/python/cpython/issues/125648",
    "lead": "Gabe Sherman",
    "date": "2024-10-17",
    "desc": "TypeError in email.message.Message.get_params"
  },
  {
    "id": "CPython #134021",
    "type": "Logical",
    "url": "https://github.com/python/cpython/issues/134021",
    "lead": "Gabe Sherman",
    "date": "2025-05-14",
    "desc": "ast.parse raises SystemError: <class 'UnicodeDecodeError'> returned a result with an error set"
  },
  {
    "id": "CPython #134151",
    "type": "Logical",
    "url": "https://github.com/python/cpython/issues/134151",
    "lead": "Gabe Sherman",
    "date": "2025-05-17",
    "desc": "TypeError: '<' not supported between instances of 'NoneType' and 'int' raised during call to email.message_from_file"
  },
  {
    "id": "CPython #134152",
    "type": "Logical",
    "url": "https://github.com/python/cpython/issues/134152",
    "lead": "Gabe Sherman",
    "date": "2025-05-17",
    "desc": "UnboundLocalError in email._header_value_parser when handling RFC 2231 parameter continuations"
  },
  {
    "id": "CPython #134155",
    "type": "Logical",
    "url": "https://github.com/python/cpython/issues/134155",
    "lead": "Gabe Sherman",
    "date": "2025-05-17",
    "desc": "AttributeError in email._header_value_parser.get_address"
  },
  {
    "id": "DateUtil #1402",
    "type": "Logical",
    "url": "https://github.com/dateutil/dateutil/issues/1402",
    "lead": "Gabe Sherman",
    "date": "2024-12-10",
    "desc": "TypeError: unsupported operand type(s) for *=: 'NoneType' and 'int' when calling tz.gettz"
  },
  {
    "id": "H5Py #2581",
    "type": "Logical",
    "url": "https://github.com/h5py/h5py/issues/2581",
    "lead": "Gabe Sherman",
    "date": "2025-05-12",
    "desc": "Provide wheel for Windows ARM64"
  },
  {
    "id": "hiredis-py #205",
    "type": "Logical",
    "url": "https://github.com/redis/hiredis-py/issues/205",
    "lead": "Gabe Sherman",
    "date": "2025-05-09",
    "desc": "Segmentation fault in Reader.gets()"
  },
  {
    "id": "hiredis-py #206",
    "type": "Logical",
    "url": "https://github.com/redis/hiredis-py/issues/206",
    "lead": "Gabe Sherman",
    "date": "2025-05-09",
    "desc": "Fix memory leaks in RESP3 map parsing"
  },
  {
    "id": "Jinja #2092",
    "type": "Logical",
    "url": "https://github.com/pallets/jinja/issues/2092",
    "lead": "Gabe Sherman",
    "date": "2025-05-12",
    "desc": "Accessing a variable has unexpected side effects on visit_Name for custom Extension"
  },
  {
    "id": "pikepdf #652",
    "type": "Logical",
    "url": "https://github.com/pikepdf/pikepdf/issues/652",
    "lead": "Gabe Sherman",
    "date": "2025-06-06",
    "desc": "UnicodeDecodeError when calling check() on an opened file"
  },
  {
    "id": "Pillow #8597",
    "type": "Logical",
    "url": "https://github.com/python-pillow/Pillow/issues/8597",
    "lead": "Gabe Sherman",
    "date": "2024-12-13",
    "desc": "ZeroDivisionError occurs when calling Image.open"
  },
  {
    "id": "Pillow #8956",
    "type": "Logical",
    "url": "https://github.com/python-pillow/Pillow/issues/8956",
    "lead": "Gabe Sherman",
    "date": "2025-05-14",
    "desc": "Unanticipated UnicodeDecodeError raised during call to PIL.Image.open"
  },
  {
    "id": "PyJSON5 #90",
    "type": "Logical",
    "url": "https://github.com/dpranke/pyjson5/issues/90",
    "lead": "Gabe Sherman",
    "date": "2025-03-27",
    "desc": "Unhandled exceptions when calling load with malformed data"
  },
  {
    "id": "PyYAML #862",
    "type": "Logical",
    "url": "https://github.com/yaml/pyyaml/issues/862",
    "lead": "Gabe Sherman",
    "date": "2025-05-10",
    "desc": "ValueError: invalid literal for int() raised from yaml.load"
  }
]
